const SHOES=[
  {
    "id": 1,
    "name": "ASICS Superblast 3",
    "brand": "ASICS",
    "category": "Super Trainer",
    "price": 210,
    "widthScore": 93,
    "width": "Excellent for wide feet",
    "cushion": 98,
    "speed": 91,
    "stability": 88,
    "value": 82,
    "longrun": 99,
    "daily": 98,
    "recovery": 86,
    "tempo": 90,
    "race": 75,
    "plate": "No",
    "note": "Best one-shoe pick for wide-foot half marathon training.",
    "foam": "FF LEAP + FF BLAST PLUS",
    "link": "https://www.google.com/search?q=ASICS+Superblast+3+running+shoe",
    "image": ""
  },
  {
    "id": 2,
    "name": "ASICS Megablast",
    "brand": "ASICS",
    "category": "Super Trainer",
    "price": 225,
    "widthScore": 82,
    "width": "Average / try on",
    "cushion": 96,
    "speed": 98,
    "stability": 82,
    "value": 78,
    "longrun": 94,
    "daily": 94,
    "recovery": 76,
    "tempo": 98,
    "race": 85,
    "plate": "No",
    "note": "Most fun and bouncy non-plated super trainer.",
    "foam": "FF TURBO\u00b2",
    "link": "https://www.google.com/search?q=ASICS+Megablast+running+shoe",
    "image": ""
  },
  {
    "id": 3,
    "name": "PUMA Deviate Pure Nitro",
    "brand": "PUMA",
    "category": "Light Super Trainer",
    "price": 150,
    "widthScore": 80,
    "width": "Average / try on",
    "cushion": 88,
    "speed": 91,
    "stability": 84,
    "value": 96,
    "longrun": 89,
    "daily": 93,
    "recovery": 80,
    "tempo": 91,
    "race": 72,
    "plate": "No",
    "note": "Best value super-trainer style daily shoe.",
    "foam": "NitroFoam",
    "link": "https://www.google.com/search?q=PUMA+Deviate+Pure+Nitro+running+shoe",
    "image": ""
  },
  {
    "id": 4,
    "name": "Nike Vomero Plus",
    "brand": "Nike",
    "category": "Max Cushion Daily",
    "price": 180,
    "widthScore": 90,
    "width": "Wide-friendly",
    "cushion": 97,
    "speed": 72,
    "stability": 83,
    "value": 82,
    "longrun": 92,
    "daily": 91,
    "recovery": 96,
    "tempo": 65,
    "race": 45,
    "plate": "No",
    "note": "Best comfort-first pick for wider feet.",
    "foam": "ZoomX",
    "link": "https://www.google.com/search?q=Nike+Vomero+Plus+running+shoe",
    "image": ""
  },
  {
    "id": 5,
    "name": "adidas Adizero Evo SL",
    "brand": "adidas",
    "category": "Fast Daily Trainer",
    "price": 150,
    "widthScore": 68,
    "width": "Narrower / caution",
    "cushion": 86,
    "speed": 96,
    "stability": 76,
    "value": 95,
    "longrun": 85,
    "daily": 90,
    "recovery": 66,
    "tempo": 96,
    "race": 82,
    "plate": "No",
    "note": "Amazing fast daily trainer, but less safe for wide feet.",
    "foam": "Lightstrike Pro",
    "link": "https://www.google.com/search?q=adidas+Adizero+Evo+SL+running+shoe",
    "image": ""
  },
  {
    "id": 6,
    "name": "PUMA Deviate Nitro 4",
    "brand": "PUMA",
    "category": "Plated Trainer",
    "price": 170,
    "widthScore": 69,
    "width": "Narrower / caution",
    "cushion": 87,
    "speed": 95,
    "stability": 82,
    "value": 89,
    "longrun": 88,
    "daily": 82,
    "recovery": 55,
    "tempo": 96,
    "race": 84,
    "plate": "Yes",
    "note": "Great workout and faster long-run shoe with elite grip.",
    "foam": "NitroFoam + PWRPLATE",
    "link": "https://www.google.com/search?q=PUMA+Deviate+Nitro+4+running+shoe",
    "image": ""
  },
  {
    "id": 7,
    "name": "ASICS Novablast 5",
    "brand": "ASICS",
    "category": "Daily Trainer",
    "price": 140,
    "widthScore": 89,
    "width": "Wide-friendly",
    "cushion": 90,
    "speed": 82,
    "stability": 80,
    "value": 92,
    "longrun": 88,
    "daily": 94,
    "recovery": 87,
    "tempo": 80,
    "race": 55,
    "plate": "No",
    "note": "Safe, practical, bouncy daily trainer.",
    "foam": "FF BLAST MAX",
    "link": "https://www.google.com/search?q=ASICS+Novablast+5+running+shoe",
    "image": ""
  },
  {
    "id": 8,
    "name": "Dynafish Xiaonian",
    "brand": "Dynafish",
    "category": "Indie Super Trainer",
    "price": 150,
    "widthScore": 65,
    "width": "Narrower / caution",
    "cushion": 88,
    "speed": 86,
    "stability": 74,
    "value": 86,
    "longrun": 83,
    "daily": 86,
    "recovery": 76,
    "tempo": 86,
    "race": 62,
    "plate": "No",
    "note": "Dark horse; harder to buy, return, and verify fit.",
    "foam": "PEBA/TPEE-style",
    "link": "https://www.google.com/search?q=Dynafish+Xiaonian+running+shoe",
    "image": ""
  },
  {
    "id": 9,
    "name": "Mizuno Neo Vista 2",
    "brand": "Mizuno",
    "category": "Long Run Trainer",
    "price": 180,
    "widthScore": 68,
    "width": "Narrower / caution",
    "cushion": 94,
    "speed": 80,
    "stability": 78,
    "value": 78,
    "longrun": 93,
    "daily": 86,
    "recovery": 91,
    "tempo": 78,
    "race": 56,
    "plate": "Nylon",
    "note": "Smooth long-run cruiser, but fit may be snug.",
    "foam": "Enerzy NXT",
    "link": "https://www.google.com/search?q=Mizuno+Neo+Vista+2+running+shoe",
    "image": ""
  },
  {
    "id": 10,
    "name": "New Balance 1080 v15",
    "brand": "New Balance",
    "category": "Max Cushion Daily",
    "price": 165,
    "widthScore": 94,
    "width": "Excellent for wide feet",
    "cushion": 95,
    "speed": 62,
    "stability": 82,
    "value": 80,
    "longrun": 84,
    "daily": 87,
    "recovery": 98,
    "tempo": 50,
    "race": 30,
    "plate": "No",
    "note": "Great plush comfort and wide sizing.",
    "foam": "Fresh Foam X",
    "link": "https://www.google.com/search?q=New+Balance+1080+v15+running+shoe",
    "image": ""
  },
  {
    "id": 11,
    "name": "R.A.D. Mallow",
    "brand": "R.A.D.",
    "category": "Cushioned Trainer",
    "price": 180,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 84,
    "speed": 60,
    "stability": 82,
    "value": 65,
    "longrun": 72,
    "daily": 76,
    "recovery": 86,
    "tempo": 50,
    "race": 25,
    "plate": "No",
    "note": "Cool option, but less proven as a running trainer.",
    "foam": "Training foam",
    "link": "https://www.google.com/search?q=R.A.D.+Mallow+running+shoe",
    "image": ""
  },
  {
    "id": 12,
    "name": "Saucony Endorphin Speed 5",
    "brand": "Saucony",
    "category": "Plated Trainer",
    "price": 145,
    "widthScore": 76,
    "width": "Average / try on",
    "cushion": 85,
    "speed": 93,
    "stability": 80,
    "value": 90,
    "longrun": 86,
    "daily": 89,
    "recovery": 79,
    "tempo": 97,
    "race": 73,
    "plate": "Yes",
    "note": "Plated Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Saucony+Endorphin+Speed+5+running+shoe",
    "image": ""
  },
  {
    "id": 13,
    "name": "Saucony Ride 18",
    "brand": "Saucony",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 82,
    "width": "Average / try on",
    "cushion": 83,
    "speed": 79,
    "stability": 86,
    "value": 88,
    "longrun": 82,
    "daily": 89,
    "recovery": 77,
    "tempo": 71,
    "race": 59,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Saucony+Ride+18+running+shoe",
    "image": ""
  },
  {
    "id": 14,
    "name": "Saucony Triumph 23",
    "brand": "Saucony",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 82,
    "width": "Average / try on",
    "cushion": 94,
    "speed": 79,
    "stability": 83,
    "value": 81,
    "longrun": 92,
    "daily": 90,
    "recovery": 98,
    "tempo": 71,
    "race": 59,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Saucony+Triumph+23+running+shoe",
    "image": ""
  },
  {
    "id": 15,
    "name": "Saucony Hurricane 25",
    "brand": "Saucony",
    "category": "Stability Max Cushion",
    "price": 185,
    "widthScore": 82,
    "width": "Average / try on",
    "cushion": 89,
    "speed": 68,
    "stability": 92,
    "value": 86,
    "longrun": 90,
    "daily": 93,
    "recovery": 94,
    "tempo": 60,
    "race": 48,
    "plate": "No",
    "note": "Stability Max Cushion option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Saucony+Hurricane+25+running+shoe",
    "image": ""
  },
  {
    "id": 16,
    "name": "Saucony Guide 18",
    "brand": "Saucony",
    "category": "Stability Daily",
    "price": 145,
    "widthScore": 82,
    "width": "Average / try on",
    "cushion": 72,
    "speed": 75,
    "stability": 91,
    "value": 85,
    "longrun": 79,
    "daily": 86,
    "recovery": 66,
    "tempo": 67,
    "race": 55,
    "plate": "No",
    "note": "Stability Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Saucony+Guide+18+running+shoe",
    "image": ""
  },
  {
    "id": 17,
    "name": "Saucony Kinvara 16",
    "brand": "Saucony",
    "category": "Light Daily Trainer",
    "price": 145,
    "widthScore": 82,
    "width": "Average / try on",
    "cushion": 83,
    "speed": 79,
    "stability": 77,
    "value": 86,
    "longrun": 79,
    "daily": 86,
    "recovery": 77,
    "tempo": 71,
    "race": 59,
    "plate": "No",
    "note": "Light Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Saucony+Kinvara+16+running+shoe",
    "image": ""
  },
  {
    "id": 18,
    "name": "Saucony Tempus 2",
    "brand": "Saucony",
    "category": "Light Stability Trainer",
    "price": 145,
    "widthScore": 82,
    "width": "Average / try on",
    "cushion": 74,
    "speed": 73,
    "stability": 91,
    "value": 84,
    "longrun": 79,
    "daily": 87,
    "recovery": 68,
    "tempo": 65,
    "race": 53,
    "plate": "No",
    "note": "Light Stability Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Saucony+Tempus+2+running+shoe",
    "image": ""
  },
  {
    "id": 19,
    "name": "Brooks Ghost 17",
    "brand": "Brooks",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 88,
    "width": "Wide-friendly",
    "cushion": 86,
    "speed": 76,
    "stability": 88,
    "value": 86,
    "longrun": 83,
    "daily": 90,
    "recovery": 80,
    "tempo": 68,
    "race": 56,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Brooks+Ghost+17+running+shoe",
    "image": ""
  },
  {
    "id": 20,
    "name": "Brooks Glycerin 22",
    "brand": "Brooks",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 88,
    "width": "Wide-friendly",
    "cushion": 90,
    "speed": 62,
    "stability": 79,
    "value": 80,
    "longrun": 84,
    "daily": 87,
    "recovery": 95,
    "tempo": 54,
    "race": 42,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Brooks+Glycerin+22+running+shoe",
    "image": ""
  },
  {
    "id": 21,
    "name": "Brooks Ghost Max 2",
    "brand": "Brooks",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 88,
    "width": "Wide-friendly",
    "cushion": 93,
    "speed": 67,
    "stability": 87,
    "value": 83,
    "longrun": 89,
    "daily": 91,
    "recovery": 98,
    "tempo": 59,
    "race": 47,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Brooks+Ghost+Max+2+running+shoe",
    "image": ""
  },
  {
    "id": 22,
    "name": "Brooks Hyperion 2",
    "brand": "Brooks",
    "category": "Light Daily Trainer",
    "price": 145,
    "widthScore": 88,
    "width": "Wide-friendly",
    "cushion": 79,
    "speed": 61,
    "stability": 85,
    "value": 86,
    "longrun": 75,
    "daily": 87,
    "recovery": 73,
    "tempo": 53,
    "race": 41,
    "plate": "No",
    "note": "Light Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Brooks+Hyperion+2+running+shoe",
    "image": ""
  },
  {
    "id": 23,
    "name": "Brooks Hyperion Max 3",
    "brand": "Brooks",
    "category": "Super Trainer",
    "price": 185,
    "widthScore": 88,
    "width": "Wide-friendly",
    "cushion": 91,
    "speed": 88,
    "stability": 87,
    "value": 84,
    "longrun": 95,
    "daily": 91,
    "recovery": 85,
    "tempo": 80,
    "race": 68,
    "plate": "No",
    "note": "Super Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Brooks+Hyperion+Max+3+running+shoe",
    "image": ""
  },
  {
    "id": 24,
    "name": "Brooks Launch 11",
    "brand": "Brooks",
    "category": "Budget Daily Trainer",
    "price": 145,
    "widthScore": 88,
    "width": "Wide-friendly",
    "cushion": 75,
    "speed": 69,
    "stability": 80,
    "value": 93,
    "longrun": 74,
    "daily": 86,
    "recovery": 69,
    "tempo": 61,
    "race": 49,
    "plate": "No",
    "note": "Budget Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Brooks+Launch+11+running+shoe",
    "image": ""
  },
  {
    "id": 25,
    "name": "Brooks Adrenaline GTS 24",
    "brand": "Brooks",
    "category": "Stability Daily",
    "price": 145,
    "widthScore": 88,
    "width": "Wide-friendly",
    "cushion": 87,
    "speed": 77,
    "stability": 95,
    "value": 88,
    "longrun": 86,
    "daily": 94,
    "recovery": 81,
    "tempo": 69,
    "race": 57,
    "plate": "No",
    "note": "Stability Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Brooks+Adrenaline+GTS+24+running+shoe",
    "image": ""
  },
  {
    "id": 26,
    "name": "Nike Pegasus 42",
    "brand": "Nike",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 88,
    "speed": 73,
    "stability": 78,
    "value": 82,
    "longrun": 79,
    "daily": 86,
    "recovery": 82,
    "tempo": 65,
    "race": 53,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Nike+Pegasus+42+running+shoe",
    "image": ""
  },
  {
    "id": 27,
    "name": "Nike Vomero 18",
    "brand": "Nike",
    "category": "Cushioned Daily",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 96,
    "speed": 61,
    "stability": 75,
    "value": 88,
    "longrun": 77,
    "daily": 90,
    "recovery": 98,
    "tempo": 53,
    "race": 41,
    "plate": "No",
    "note": "Cushioned Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Nike+Vomero+18+running+shoe",
    "image": ""
  },
  {
    "id": 28,
    "name": "Nike Structure 26",
    "brand": "Nike",
    "category": "Stability Daily",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 72,
    "speed": 64,
    "stability": 90,
    "value": 76,
    "longrun": 75,
    "daily": 83,
    "recovery": 66,
    "tempo": 56,
    "race": 44,
    "plate": "No",
    "note": "Stability Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Nike+Structure+26+running+shoe",
    "image": ""
  },
  {
    "id": 29,
    "name": "Nike Invincible 3",
    "brand": "Nike",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 89,
    "speed": 74,
    "stability": 88,
    "value": 82,
    "longrun": 90,
    "daily": 90,
    "recovery": 94,
    "tempo": 66,
    "race": 54,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Nike+Invincible+3+running+shoe",
    "image": ""
  },
  {
    "id": 30,
    "name": "Nike Streakfly 2",
    "brand": "Nike",
    "category": "Speed Shoe",
    "price": 145,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 87,
    "speed": 94,
    "stability": 75,
    "value": 76,
    "longrun": 85,
    "daily": 83,
    "recovery": 81,
    "tempo": 98,
    "race": 74,
    "plate": "No",
    "note": "Speed Shoe option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Nike+Streakfly+2+running+shoe",
    "image": ""
  },
  {
    "id": 31,
    "name": "Nike Zoom Fly 6",
    "brand": "Nike",
    "category": "Plated Trainer",
    "price": 145,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 83,
    "speed": 90,
    "stability": 88,
    "value": 90,
    "longrun": 87,
    "daily": 91,
    "recovery": 77,
    "tempo": 94,
    "race": 70,
    "plate": "Yes",
    "note": "Plated Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Nike+Zoom+Fly+6+running+shoe",
    "image": ""
  },
  {
    "id": 32,
    "name": "Nike Vomero Premium",
    "brand": "Nike",
    "category": "Ultra Max Cushion",
    "price": 185,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 95,
    "speed": 67,
    "stability": 81,
    "value": 91,
    "longrun": 88,
    "daily": 93,
    "recovery": 98,
    "tempo": 59,
    "race": 47,
    "plate": "No",
    "note": "Ultra Max Cushion option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Nike+Vomero+Premium+running+shoe",
    "image": ""
  },
  {
    "id": 33,
    "name": "adidas Supernova Rise 2",
    "brand": "adidas",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 87,
    "speed": 69,
    "stability": 88,
    "value": 76,
    "longrun": 81,
    "daily": 87,
    "recovery": 81,
    "tempo": 61,
    "race": 49,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=adidas+Supernova+Rise+2+running+shoe",
    "image": ""
  },
  {
    "id": 34,
    "name": "adidas Supernova Prima 2",
    "brand": "adidas",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 90,
    "speed": 66,
    "stability": 77,
    "value": 90,
    "longrun": 84,
    "daily": 89,
    "recovery": 95,
    "tempo": 58,
    "race": 46,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=adidas+Supernova+Prima+2+running+shoe",
    "image": ""
  },
  {
    "id": 35,
    "name": "adidas Boston 13",
    "brand": "adidas",
    "category": "Workout Trainer",
    "price": 145,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 84,
    "speed": 73,
    "stability": 86,
    "value": 79,
    "longrun": 81,
    "daily": 87,
    "recovery": 78,
    "tempo": 65,
    "race": 53,
    "plate": "No",
    "note": "Workout Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=adidas+Boston+13+running+shoe",
    "image": ""
  },
  {
    "id": 36,
    "name": "adidas Adizero SL2",
    "brand": "adidas",
    "category": "Fast Daily Trainer",
    "price": 145,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 81,
    "speed": 74,
    "stability": 79,
    "value": 94,
    "longrun": 78,
    "daily": 88,
    "recovery": 75,
    "tempo": 66,
    "race": 54,
    "plate": "No",
    "note": "Fast Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=adidas+Adizero+SL2+running+shoe",
    "image": ""
  },
  {
    "id": 37,
    "name": "adidas Prime X 2 Strung",
    "brand": "adidas",
    "category": "Max Super Trainer",
    "price": 185,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 94,
    "speed": 95,
    "stability": 73,
    "value": 80,
    "longrun": 94,
    "daily": 86,
    "recovery": 98,
    "tempo": 87,
    "race": 75,
    "plate": "No",
    "note": "Max Super Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=adidas+Prime+X+2+Strung+running+shoe",
    "image": ""
  },
  {
    "id": 38,
    "name": "adidas Adios Pro 5",
    "brand": "adidas",
    "category": "Race Shoe",
    "price": 250,
    "widthScore": 66,
    "width": "Narrower / caution",
    "cushion": 81,
    "speed": 95,
    "stability": 82,
    "value": 83,
    "longrun": 86,
    "daily": 86,
    "recovery": 75,
    "tempo": 87,
    "race": 99,
    "plate": "Yes",
    "note": "Race Shoe option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=adidas+Adios+Pro+5+running+shoe",
    "image": ""
  },
  {
    "id": 39,
    "name": "HOKA Clifton 10",
    "brand": "HOKA",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 84,
    "width": "Average / try on",
    "cushion": 82,
    "speed": 66,
    "stability": 75,
    "value": 91,
    "longrun": 74,
    "daily": 86,
    "recovery": 76,
    "tempo": 58,
    "race": 46,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=HOKA+Clifton+10+running+shoe",
    "image": ""
  },
  {
    "id": 40,
    "name": "HOKA Bondi 9",
    "brand": "HOKA",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 84,
    "width": "Average / try on",
    "cushion": 88,
    "speed": 80,
    "stability": 74,
    "value": 94,
    "longrun": 87,
    "daily": 89,
    "recovery": 93,
    "tempo": 72,
    "race": 60,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=HOKA+Bondi+9+running+shoe",
    "image": ""
  },
  {
    "id": 41,
    "name": "HOKA Mach 6",
    "brand": "HOKA",
    "category": "Light Daily Trainer",
    "price": 145,
    "widthScore": 84,
    "width": "Average / try on",
    "cushion": 84,
    "speed": 63,
    "stability": 83,
    "value": 90,
    "longrun": 76,
    "daily": 89,
    "recovery": 78,
    "tempo": 55,
    "race": 43,
    "plate": "No",
    "note": "Light Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=HOKA+Mach+6+running+shoe",
    "image": ""
  },
  {
    "id": 42,
    "name": "HOKA Mach X 3",
    "brand": "HOKA",
    "category": "Plated Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 79,
    "speed": 95,
    "stability": 84,
    "value": 81,
    "longrun": 86,
    "daily": 85,
    "recovery": 73,
    "tempo": 98,
    "race": 75,
    "plate": "Yes",
    "note": "Plated Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=HOKA+Mach+X+3+running+shoe",
    "image": ""
  },
  {
    "id": 43,
    "name": "HOKA Skyflow 2",
    "brand": "HOKA",
    "category": "Cushioned Daily",
    "price": 145,
    "widthScore": 84,
    "width": "Average / try on",
    "cushion": 91,
    "speed": 75,
    "stability": 88,
    "value": 85,
    "longrun": 84,
    "daily": 92,
    "recovery": 96,
    "tempo": 67,
    "race": 55,
    "plate": "No",
    "note": "Cushioned Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=HOKA+Skyflow+2+running+shoe",
    "image": ""
  },
  {
    "id": 44,
    "name": "HOKA Arahi 8",
    "brand": "HOKA",
    "category": "Stability Daily",
    "price": 145,
    "widthScore": 84,
    "width": "Average / try on",
    "cushion": 78,
    "speed": 84,
    "stability": 91,
    "value": 85,
    "longrun": 84,
    "daily": 88,
    "recovery": 72,
    "tempo": 76,
    "race": 64,
    "plate": "No",
    "note": "Stability Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=HOKA+Arahi+8+running+shoe",
    "image": ""
  },
  {
    "id": 45,
    "name": "HOKA Gaviota 6",
    "brand": "HOKA",
    "category": "Stability Max Cushion",
    "price": 185,
    "widthScore": 84,
    "width": "Average / try on",
    "cushion": 90,
    "speed": 76,
    "stability": 93,
    "value": 76,
    "longrun": 93,
    "daily": 90,
    "recovery": 95,
    "tempo": 68,
    "race": 56,
    "plate": "No",
    "note": "Stability Max Cushion option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=HOKA+Gaviota+6+running+shoe",
    "image": ""
  },
  {
    "id": 46,
    "name": "New Balance Rebel v5",
    "brand": "New Balance",
    "category": "Fast Daily Trainer",
    "price": 145,
    "widthScore": 89,
    "width": "Wide-friendly",
    "cushion": 81,
    "speed": 68,
    "stability": 80,
    "value": 78,
    "longrun": 76,
    "daily": 83,
    "recovery": 75,
    "tempo": 60,
    "race": 48,
    "plate": "No",
    "note": "Fast Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=New+Balance+Rebel+v5+running+shoe",
    "image": ""
  },
  {
    "id": 47,
    "name": "New Balance 880 v15",
    "brand": "New Balance",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 89,
    "width": "Wide-friendly",
    "cushion": 75,
    "speed": 67,
    "stability": 81,
    "value": 83,
    "longrun": 74,
    "daily": 83,
    "recovery": 69,
    "tempo": 59,
    "race": 47,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=New+Balance+880+v15+running+shoe",
    "image": ""
  },
  {
    "id": 48,
    "name": "New Balance More v6",
    "brand": "New Balance",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 89,
    "width": "Wide-friendly",
    "cushion": 97,
    "speed": 83,
    "stability": 78,
    "value": 94,
    "longrun": 93,
    "daily": 93,
    "recovery": 98,
    "tempo": 75,
    "race": 63,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=New+Balance+More+v6+running+shoe",
    "image": ""
  },
  {
    "id": 49,
    "name": "New Balance Balos v2",
    "brand": "New Balance",
    "category": "Super Trainer",
    "price": 185,
    "widthScore": 89,
    "width": "Wide-friendly",
    "cushion": 97,
    "speed": 97,
    "stability": 83,
    "value": 88,
    "longrun": 99,
    "daily": 93,
    "recovery": 91,
    "tempo": 89,
    "race": 77,
    "plate": "No",
    "note": "Super Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=New+Balance+Balos+v2+running+shoe",
    "image": ""
  },
  {
    "id": 50,
    "name": "New Balance SC Trainer v4",
    "brand": "New Balance",
    "category": "Plated Trainer",
    "price": 145,
    "widthScore": 83,
    "width": "Average / try on",
    "cushion": 80,
    "speed": 99,
    "stability": 83,
    "value": 87,
    "longrun": 87,
    "daily": 87,
    "recovery": 74,
    "tempo": 98,
    "race": 79,
    "plate": "Yes",
    "note": "Plated Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=New+Balance+SC+Trainer+v4+running+shoe",
    "image": ""
  },
  {
    "id": 51,
    "name": "PUMA Velocity Nitro 4",
    "brand": "PUMA",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 78,
    "speed": 59,
    "stability": 82,
    "value": 91,
    "longrun": 73,
    "daily": 87,
    "recovery": 72,
    "tempo": 51,
    "race": 39,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=PUMA+Velocity+Nitro+4+running+shoe",
    "image": ""
  },
  {
    "id": 52,
    "name": "PUMA Magnify Nitro 3",
    "brand": "PUMA",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 94,
    "speed": 74,
    "stability": 81,
    "value": 84,
    "longrun": 90,
    "daily": 90,
    "recovery": 98,
    "tempo": 66,
    "race": 54,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=PUMA+Magnify+Nitro+3+running+shoe",
    "image": ""
  },
  {
    "id": 53,
    "name": "PUMA ForeverRun Nitro 2",
    "brand": "PUMA",
    "category": "Stability Daily",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 85,
    "speed": 69,
    "stability": 92,
    "value": 78,
    "longrun": 82,
    "daily": 89,
    "recovery": 79,
    "tempo": 61,
    "race": 49,
    "plate": "No",
    "note": "Stability Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=PUMA+ForeverRun+Nitro+2+running+shoe",
    "image": ""
  },
  {
    "id": 54,
    "name": "PUMA Fast-R Nitro Elite 3",
    "brand": "PUMA",
    "category": "Race Shoe",
    "price": 250,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 80,
    "speed": 98,
    "stability": 73,
    "value": 94,
    "longrun": 83,
    "daily": 86,
    "recovery": 74,
    "tempo": 90,
    "race": 99,
    "plate": "Yes",
    "note": "Race Shoe option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=PUMA+Fast-R+Nitro+Elite+3+running+shoe",
    "image": ""
  },
  {
    "id": 55,
    "name": "PUMA Deviate Nitro Elite 3",
    "brand": "PUMA",
    "category": "Race Shoe",
    "price": 250,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 74,
    "speed": 91,
    "stability": 75,
    "value": 91,
    "longrun": 80,
    "daily": 84,
    "recovery": 68,
    "tempo": 83,
    "race": 99,
    "plate": "Yes",
    "note": "Race Shoe option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=PUMA+Deviate+Nitro+Elite+3+running+shoe",
    "image": ""
  },
  {
    "id": 56,
    "name": "ASICS Gel-Nimbus 27",
    "brand": "ASICS",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 86,
    "width": "Wide-friendly",
    "cushion": 94,
    "speed": 65,
    "stability": 83,
    "value": 84,
    "longrun": 87,
    "daily": 91,
    "recovery": 98,
    "tempo": 57,
    "race": 45,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=ASICS+Gel-Nimbus+27+running+shoe",
    "image": ""
  },
  {
    "id": 57,
    "name": "ASICS Gel-Cumulus 27",
    "brand": "ASICS",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 86,
    "width": "Wide-friendly",
    "cushion": 84,
    "speed": 71,
    "stability": 75,
    "value": 94,
    "longrun": 76,
    "daily": 88,
    "recovery": 78,
    "tempo": 63,
    "race": 51,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=ASICS+Gel-Cumulus+27+running+shoe",
    "image": ""
  },
  {
    "id": 58,
    "name": "ASICS Gel-Kayano 33",
    "brand": "ASICS",
    "category": "Stability Max Cushion",
    "price": 185,
    "widthScore": 86,
    "width": "Wide-friendly",
    "cushion": 95,
    "speed": 76,
    "stability": 97,
    "value": 83,
    "longrun": 96,
    "daily": 95,
    "recovery": 98,
    "tempo": 68,
    "race": 56,
    "plate": "No",
    "note": "Stability Max Cushion option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=ASICS+Gel-Kayano+33+running+shoe",
    "image": ""
  },
  {
    "id": 59,
    "name": "ASICS GT-2000 14",
    "brand": "ASICS",
    "category": "Stability Daily",
    "price": 145,
    "widthScore": 86,
    "width": "Wide-friendly",
    "cushion": 84,
    "speed": 82,
    "stability": 93,
    "value": 88,
    "longrun": 86,
    "daily": 92,
    "recovery": 78,
    "tempo": 74,
    "race": 62,
    "plate": "No",
    "note": "Stability Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=ASICS+GT-2000+14+running+shoe",
    "image": ""
  },
  {
    "id": 60,
    "name": "ASICS Magic Speed 4",
    "brand": "ASICS",
    "category": "Plated Trainer",
    "price": 145,
    "widthScore": 80,
    "width": "Average / try on",
    "cushion": 74,
    "speed": 97,
    "stability": 82,
    "value": 82,
    "longrun": 84,
    "daily": 83,
    "recovery": 68,
    "tempo": 98,
    "race": 77,
    "plate": "Yes",
    "note": "Plated Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=ASICS+Magic+Speed+4+running+shoe",
    "image": ""
  },
  {
    "id": 61,
    "name": "ASICS GlideRide Max",
    "brand": "ASICS",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 86,
    "width": "Wide-friendly",
    "cushion": 91,
    "speed": 76,
    "stability": 85,
    "value": 79,
    "longrun": 91,
    "daily": 89,
    "recovery": 96,
    "tempo": 68,
    "race": 56,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=ASICS+GlideRide+Max+running+shoe",
    "image": ""
  },
  {
    "id": 62,
    "name": "ASICS Noosa Tri 16",
    "brand": "ASICS",
    "category": "Light Daily Trainer",
    "price": 145,
    "widthScore": 86,
    "width": "Wide-friendly",
    "cushion": 79,
    "speed": 79,
    "stability": 75,
    "value": 77,
    "longrun": 77,
    "daily": 81,
    "recovery": 73,
    "tempo": 71,
    "race": 59,
    "plate": "No",
    "note": "Light Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=ASICS+Noosa+Tri+16+running+shoe",
    "image": ""
  },
  {
    "id": 63,
    "name": "Mizuno Wave Rider 29",
    "brand": "Mizuno",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 72,
    "speed": 74,
    "stability": 73,
    "value": 78,
    "longrun": 73,
    "daily": 78,
    "recovery": 66,
    "tempo": 66,
    "race": 54,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Mizuno+Wave+Rider+29+running+shoe",
    "image": ""
  },
  {
    "id": 64,
    "name": "Mizuno Wave Sky 9",
    "brand": "Mizuno",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 92,
    "speed": 60,
    "stability": 76,
    "value": 77,
    "longrun": 83,
    "daily": 85,
    "recovery": 97,
    "tempo": 52,
    "race": 40,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Mizuno+Wave+Sky+9+running+shoe",
    "image": ""
  },
  {
    "id": 65,
    "name": "Mizuno Neo Zen",
    "brand": "Mizuno",
    "category": "Light Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 74,
    "speed": 64,
    "stability": 88,
    "value": 76,
    "longrun": 75,
    "daily": 83,
    "recovery": 68,
    "tempo": 56,
    "race": 44,
    "plate": "No",
    "note": "Light Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Mizuno+Neo+Zen+running+shoe",
    "image": ""
  },
  {
    "id": 66,
    "name": "Mizuno Wave Inspire 21",
    "brand": "Mizuno",
    "category": "Stability Daily",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 81,
    "speed": 67,
    "stability": 91,
    "value": 92,
    "longrun": 79,
    "daily": 92,
    "recovery": 75,
    "tempo": 59,
    "race": 47,
    "plate": "No",
    "note": "Stability Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Mizuno+Wave+Inspire+21+running+shoe",
    "image": ""
  },
  {
    "id": 67,
    "name": "On Cloudsurfer 2",
    "brand": "On",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 81,
    "speed": 73,
    "stability": 78,
    "value": 87,
    "longrun": 77,
    "daily": 86,
    "recovery": 75,
    "tempo": 65,
    "race": 53,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=On+Cloudsurfer+2+running+shoe",
    "image": ""
  },
  {
    "id": 68,
    "name": "On Cloudmonster 2",
    "brand": "On",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 94,
    "speed": 69,
    "stability": 74,
    "value": 91,
    "longrun": 86,
    "daily": 90,
    "recovery": 98,
    "tempo": 61,
    "race": 49,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=On+Cloudmonster+2+running+shoe",
    "image": ""
  },
  {
    "id": 69,
    "name": "On Cloudmonster Hyper",
    "brand": "On",
    "category": "Super Trainer",
    "price": 185,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 95,
    "speed": 88,
    "stability": 87,
    "value": 85,
    "longrun": 97,
    "daily": 93,
    "recovery": 89,
    "tempo": 80,
    "race": 68,
    "plate": "No",
    "note": "Super Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=On+Cloudmonster+Hyper+running+shoe",
    "image": ""
  },
  {
    "id": 70,
    "name": "On Cloudrunner 2",
    "brand": "On",
    "category": "Stability Daily",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 87,
    "speed": 60,
    "stability": 93,
    "value": 94,
    "longrun": 80,
    "daily": 95,
    "recovery": 81,
    "tempo": 52,
    "race": 40,
    "plate": "No",
    "note": "Stability Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=On+Cloudrunner+2+running+shoe",
    "image": ""
  },
  {
    "id": 71,
    "name": "Altra Experience Flow 3",
    "brand": "Altra",
    "category": "Wide Toe Box Daily",
    "price": 145,
    "widthScore": 97,
    "width": "Excellent for wide feet",
    "cushion": 78,
    "speed": 73,
    "stability": 87,
    "value": 78,
    "longrun": 79,
    "daily": 85,
    "recovery": 72,
    "tempo": 65,
    "race": 53,
    "plate": "No",
    "note": "Wide Toe Box Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Altra+Experience+Flow+3+running+shoe",
    "image": ""
  },
  {
    "id": 72,
    "name": "Altra Torin 8",
    "brand": "Altra",
    "category": "Wide Toe Box Daily",
    "price": 145,
    "widthScore": 97,
    "width": "Excellent for wide feet",
    "cushion": 72,
    "speed": 70,
    "stability": 75,
    "value": 81,
    "longrun": 72,
    "daily": 80,
    "recovery": 66,
    "tempo": 62,
    "race": 50,
    "plate": "No",
    "note": "Wide Toe Box Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Altra+Torin+8+running+shoe",
    "image": ""
  },
  {
    "id": 73,
    "name": "Altra FWD Via",
    "brand": "Altra",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 97,
    "width": "Excellent for wide feet",
    "cushion": 88,
    "speed": 73,
    "stability": 85,
    "value": 79,
    "longrun": 89,
    "daily": 88,
    "recovery": 93,
    "tempo": 65,
    "race": 53,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Altra+FWD+Via+running+shoe",
    "image": ""
  },
  {
    "id": 74,
    "name": "Altra Vanish Tempo 2",
    "brand": "Altra",
    "category": "Fast Daily Trainer",
    "price": 145,
    "widthScore": 97,
    "width": "Excellent for wide feet",
    "cushion": 77,
    "speed": 73,
    "stability": 75,
    "value": 77,
    "longrun": 75,
    "daily": 80,
    "recovery": 71,
    "tempo": 65,
    "race": 53,
    "plate": "No",
    "note": "Fast Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Altra+Vanish+Tempo+2+running+shoe",
    "image": ""
  },
  {
    "id": 75,
    "name": "Topo Phantom 4",
    "brand": "Topo Athletic",
    "category": "Wide Toe Box Cushion",
    "price": 145,
    "widthScore": 96,
    "width": "Excellent for wide feet",
    "cushion": 96,
    "speed": 59,
    "stability": 85,
    "value": 93,
    "longrun": 80,
    "daily": 95,
    "recovery": 98,
    "tempo": 51,
    "race": 39,
    "plate": "No",
    "note": "Wide Toe Box Cushion option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Topo+Phantom+4+running+shoe",
    "image": ""
  },
  {
    "id": 76,
    "name": "Topo Cyclone 3",
    "brand": "Topo Athletic",
    "category": "Fast Daily Trainer",
    "price": 145,
    "widthScore": 96,
    "width": "Excellent for wide feet",
    "cushion": 85,
    "speed": 73,
    "stability": 78,
    "value": 81,
    "longrun": 78,
    "daily": 85,
    "recovery": 79,
    "tempo": 65,
    "race": 53,
    "plate": "No",
    "note": "Fast Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Topo+Cyclone+3+running+shoe",
    "image": ""
  },
  {
    "id": 77,
    "name": "Topo Atmos 2",
    "brand": "Topo Athletic",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 96,
    "width": "Excellent for wide feet",
    "cushion": 95,
    "speed": 64,
    "stability": 77,
    "value": 77,
    "longrun": 85,
    "daily": 87,
    "recovery": 98,
    "tempo": 56,
    "race": 44,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Topo+Atmos+2+running+shoe",
    "image": ""
  },
  {
    "id": 78,
    "name": "Topo Specter 2",
    "brand": "Topo Athletic",
    "category": "Light Super Trainer",
    "price": 185,
    "widthScore": 96,
    "width": "Excellent for wide feet",
    "cushion": 95,
    "speed": 92,
    "stability": 81,
    "value": 76,
    "longrun": 96,
    "daily": 88,
    "recovery": 89,
    "tempo": 84,
    "race": 72,
    "plate": "No",
    "note": "Light Super Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Topo+Specter+2+running+shoe",
    "image": ""
  },
  {
    "id": 79,
    "name": "Topo Ultrafly 5",
    "brand": "Topo Athletic",
    "category": "Stability Daily",
    "price": 145,
    "widthScore": 96,
    "width": "Excellent for wide feet",
    "cushion": 84,
    "speed": 77,
    "stability": 93,
    "value": 86,
    "longrun": 84,
    "daily": 91,
    "recovery": 78,
    "tempo": 69,
    "race": 57,
    "plate": "No",
    "note": "Stability Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Topo+Ultrafly+5+running+shoe",
    "image": ""
  },
  {
    "id": 80,
    "name": "Skechers GO RUN Ride 12",
    "brand": "Skechers",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 86,
    "speed": 64,
    "stability": 84,
    "value": 90,
    "longrun": 78,
    "daily": 90,
    "recovery": 80,
    "tempo": 56,
    "race": 44,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Skechers+GO+RUN+Ride+12+running+shoe",
    "image": ""
  },
  {
    "id": 81,
    "name": "Skechers Max Cushioning Elite 3",
    "brand": "Skechers",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 97,
    "speed": 69,
    "stability": 83,
    "value": 76,
    "longrun": 90,
    "daily": 89,
    "recovery": 98,
    "tempo": 61,
    "race": 49,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Skechers+Max+Cushioning+Elite+3+running+shoe",
    "image": ""
  },
  {
    "id": 82,
    "name": "Skechers Razor 5",
    "brand": "Skechers",
    "category": "Fast Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 79,
    "speed": 81,
    "stability": 73,
    "value": 94,
    "longrun": 77,
    "daily": 86,
    "recovery": 73,
    "tempo": 73,
    "race": 61,
    "plate": "No",
    "note": "Fast Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Skechers+Razor+5+running+shoe",
    "image": ""
  },
  {
    "id": 83,
    "name": "Under Armour Infinite Elite 2",
    "brand": "Under Armour",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 83,
    "speed": 77,
    "stability": 79,
    "value": 87,
    "longrun": 79,
    "daily": 87,
    "recovery": 77,
    "tempo": 69,
    "race": 57,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Under+Armour+Infinite+Elite+2+running+shoe",
    "image": ""
  },
  {
    "id": 84,
    "name": "Under Armour Velociti Elite 3",
    "brand": "Under Armour",
    "category": "Race Shoe",
    "price": 250,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 82,
    "speed": 98,
    "stability": 86,
    "value": 93,
    "longrun": 88,
    "daily": 91,
    "recovery": 76,
    "tempo": 90,
    "race": 99,
    "plate": "Yes",
    "note": "Race Shoe option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Under+Armour+Velociti+Elite+3+running+shoe",
    "image": ""
  },
  {
    "id": 85,
    "name": "Diadora Cellula 2",
    "brand": "Diadora",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 89,
    "speed": 79,
    "stability": 74,
    "value": 85,
    "longrun": 87,
    "daily": 86,
    "recovery": 94,
    "tempo": 71,
    "race": 59,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Diadora+Cellula+2+running+shoe",
    "image": ""
  },
  {
    "id": 86,
    "name": "Diadora Atomo V7000 2",
    "brand": "Diadora",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 83,
    "speed": 60,
    "stability": 85,
    "value": 84,
    "longrun": 76,
    "daily": 88,
    "recovery": 77,
    "tempo": 52,
    "race": 40,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Diadora+Atomo+V7000+2+running+shoe",
    "image": ""
  },
  {
    "id": 87,
    "name": "Mount to Coast R1",
    "brand": "Mount to Coast",
    "category": "Ultra Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 78,
    "speed": 61,
    "stability": 74,
    "value": 78,
    "longrun": 71,
    "daily": 80,
    "recovery": 72,
    "tempo": 53,
    "race": 41,
    "plate": "No",
    "note": "Ultra Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Mount+to+Coast+R1+running+shoe",
    "image": ""
  },
  {
    "id": 88,
    "name": "Mount to Coast P1",
    "brand": "Mount to Coast",
    "category": "Cushioned Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 96,
    "speed": 64,
    "stability": 81,
    "value": 92,
    "longrun": 80,
    "daily": 93,
    "recovery": 98,
    "tempo": 56,
    "race": 44,
    "plate": "No",
    "note": "Cushioned Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Mount+to+Coast+P1+running+shoe",
    "image": ""
  },
  {
    "id": 89,
    "name": "Craft Pacer 2",
    "brand": "Craft",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 75,
    "speed": 62,
    "stability": 77,
    "value": 86,
    "longrun": 71,
    "daily": 83,
    "recovery": 69,
    "tempo": 54,
    "race": 42,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Craft+Pacer+2+running+shoe",
    "image": ""
  },
  {
    "id": 90,
    "name": "Craft Nordlite Ultra 2",
    "brand": "Craft",
    "category": "Road/Trail Ultra",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 80,
    "speed": 60,
    "stability": 86,
    "value": 76,
    "longrun": 75,
    "daily": 84,
    "recovery": 74,
    "tempo": 52,
    "race": 40,
    "plate": "No",
    "note": "Road/Trail Ultra option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Craft+Nordlite+Ultra+2+running+shoe",
    "image": ""
  },
  {
    "id": 91,
    "name": "Salomon Aero Glide 3",
    "brand": "Salomon",
    "category": "Max Cushion Daily",
    "price": 185,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 97,
    "speed": 75,
    "stability": 87,
    "value": 84,
    "longrun": 93,
    "daily": 93,
    "recovery": 98,
    "tempo": 67,
    "race": 55,
    "plate": "No",
    "note": "Max Cushion Daily option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Salomon+Aero+Glide+3+running+shoe",
    "image": ""
  },
  {
    "id": 92,
    "name": "Salomon Aero Blaze 3",
    "brand": "Salomon",
    "category": "Light Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 72,
    "speed": 70,
    "stability": 72,
    "value": 76,
    "longrun": 71,
    "daily": 77,
    "recovery": 66,
    "tempo": 62,
    "race": 50,
    "plate": "No",
    "note": "Light Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Salomon+Aero+Blaze+3+running+shoe",
    "image": ""
  },
  {
    "id": 93,
    "name": "Li-Ning Red Hare 9 Ultra",
    "brand": "Li-Ning",
    "category": "Indie Super Trainer",
    "price": 185,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 95,
    "speed": 92,
    "stability": 80,
    "value": 90,
    "longrun": 96,
    "daily": 92,
    "recovery": 89,
    "tempo": 84,
    "race": 72,
    "plate": "No",
    "note": "Indie Super Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Li-Ning+Red+Hare+9+Ultra+running+shoe",
    "image": ""
  },
  {
    "id": 94,
    "name": "Kiprun KD900X LD 2",
    "brand": "Kiprun",
    "category": "Plated Trainer",
    "price": 145,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 82,
    "speed": 98,
    "stability": 73,
    "value": 80,
    "longrun": 84,
    "daily": 82,
    "recovery": 76,
    "tempo": 98,
    "race": 78,
    "plate": "Yes",
    "note": "Plated Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Kiprun+KD900X+LD+2+running+shoe",
    "image": ""
  },
  {
    "id": 95,
    "name": "Kiprun Kipstorm Tempo",
    "brand": "Kiprun",
    "category": "Fast Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 72,
    "speed": 65,
    "stability": 73,
    "value": 76,
    "longrun": 70,
    "daily": 77,
    "recovery": 66,
    "tempo": 57,
    "race": 45,
    "plate": "No",
    "note": "Fast Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Kiprun+Kipstorm+Tempo+running+shoe",
    "image": ""
  },
  {
    "id": 96,
    "name": "361\u00b0 Flame 4",
    "brand": "361 Degrees",
    "category": "Plated Trainer",
    "price": 145,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 83,
    "speed": 90,
    "stability": 83,
    "value": 89,
    "longrun": 85,
    "daily": 89,
    "recovery": 77,
    "tempo": 94,
    "race": 70,
    "plate": "Yes",
    "note": "Plated Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=361\u00b0+Flame+4+running+shoe",
    "image": ""
  },
  {
    "id": 97,
    "name": "361\u00b0 Meraki 6",
    "brand": "361 Degrees",
    "category": "Daily Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 88,
    "speed": 64,
    "stability": 76,
    "value": 83,
    "longrun": 76,
    "daily": 86,
    "recovery": 82,
    "tempo": 56,
    "race": 44,
    "plate": "No",
    "note": "Daily Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=361\u00b0+Meraki+6+running+shoe",
    "image": ""
  },
  {
    "id": 98,
    "name": "TYR Valkyrie Elite Carbon",
    "brand": "TYR",
    "category": "Race Shoe",
    "price": 250,
    "widthScore": 72,
    "width": "Narrower / caution",
    "cushion": 75,
    "speed": 91,
    "stability": 88,
    "value": 76,
    "longrun": 84,
    "daily": 83,
    "recovery": 69,
    "tempo": 83,
    "race": 99,
    "plate": "Yes",
    "note": "Race Shoe option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=TYR+Valkyrie+Elite+Carbon+running+shoe",
    "image": ""
  },
  {
    "id": 99,
    "name": "TYR Valkyrie SpeedWorks",
    "brand": "TYR",
    "category": "Fast Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 77,
    "speed": 60,
    "stability": 80,
    "value": 81,
    "longrun": 72,
    "daily": 83,
    "recovery": 71,
    "tempo": 52,
    "race": 40,
    "plate": "No",
    "note": "Fast Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=TYR+Valkyrie+SpeedWorks+running+shoe",
    "image": ""
  },
  {
    "id": 100,
    "name": "Norda 005",
    "brand": "Norda",
    "category": "Trail/Ultra Trainer",
    "price": 145,
    "widthScore": 78,
    "width": "Average / try on",
    "cushion": 84,
    "speed": 81,
    "stability": 88,
    "value": 85,
    "longrun": 84,
    "daily": 89,
    "recovery": 78,
    "tempo": 73,
    "race": 61,
    "plate": "No",
    "note": "Trail/Ultra Trainer option worth comparing.",
    "foam": "See retailer",
    "link": "https://www.google.com/search?q=Norda+005+running+shoe",
    "image": ""
  }
];