const state={goal:'half',fit:'wide',focus:'balanced',budget:'999'};let step=0;
const els={q:document.getElementById('q'),category:document.getElementById('category'),grid:document.getElementById('grid'),count:document.getElementById('count'),liveTitle:document.getElementById('liveTitle'),liveSummary:document.getElementById('liveSummary'),liveReasons:document.getElementById('liveReasons'),reportSummary:document.getElementById('reportSummary'),perfectMatch:document.getElementById('perfectMatch'),topFive:document.getElementById('topFive'),nearMisses:document.getElementById('nearMisses'),avoidList:document.getElementById('avoidList'),rotation:document.getElementById('rotation'),stepper:document.getElementById('stepper')};
[...new Set(SHOES.map(s=>s.category))].sort().forEach(c=>{let o=document.createElement('option');o.value=c;o.textContent=c;els.category.appendChild(o)});
let selected=new Set(JSON.parse(localStorage.getItem('selectedShoesV7')||'[]'));
function widthClass(s){return s.widthScore>=85?'good':s.widthScore<75?'bad':'warn'}
function labelFor(group,val){let btn=document.querySelector(`[data-group="${group}"] [data-value="${val}"]`);return btn?btn.textContent:val}
function likedTerms(){return (document.getElementById('likedShoes').value||'').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean)}
function avoidTerms(){return (document.getElementById('avoidInput').value||'').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean)}
function score(s){let g=state.goal,f=state.fit,focus=state.focus,b=0;if(g==='5k')b=s.speed*.34+s.tempo*.28+s.race*.18+s.value*.10+s.stability*.05+s.daily*.05;if(g==='10k')b=s.speed*.28+s.tempo*.28+s.race*.16+s.daily*.12+s.cushion*.08+s.value*.08;if(g==='10miler')b=s.tempo*.24+s.longrun*.22+s.speed*.18+s.cushion*.14+s.daily*.12+s.value*.10;if(g==='half'||g==='sub2')b=s.daily*.22+s.longrun*.25+s.tempo*.20+s.speed*.14+s.cushion*.10+s.stability*.05+s.value*.04;if(g==='marathon')b=s.longrun*.32+s.cushion*.22+s.daily*.16+s.stability*.12+s.tempo*.10+s.value*.08;if(g==='ultra')b=s.longrun*.35+s.cushion*.25+s.stability*.18+s.recovery*.12+s.value*.10;if(g==='daily')b=s.daily*.32+s.cushion*.18+s.stability*.15+s.value*.15+s.recovery*.10+s.longrun*.10;if(f==='wide')b+=(s.widthScore-75)*.28;if(f==='extraWide')b+=(s.widthScore-75)*.45;if(f==='standard'||f==='unknown')b+=Math.min(s.widthScore,85)*.03;if(f==='narrow')b+=s.speed*.04;if(focus==='cushion')b+=s.cushion*.18;if(focus==='speed')b+=s.speed*.18;if(focus==='stable')b+=s.stability*.18;if(focus==='value')b+=s.value*.20-(s.price>200?4:0);if(focus==='nonplate'&&s.plate==='No')b+=8;if(focus==='nonplate'&&s.plate!=='No')b-=7;if(focus==='race')b+=s.race*.18;likedTerms().forEach(t=>{if(JSON.stringify(s).toLowerCase().includes(t))b+=5});avoidTerms().forEach(t=>{if(JSON.stringify(s).toLowerCase().includes(t))b-=10;if(t==='narrow'&&s.widthScore<75)b-=12;if(t==='plated'&&s.plate!=='No')b-=10;if(t==='firm'&&s.cushion<82)b-=8});return Math.round(Math.max(0,Math.min(100,b)))}
function filtered(){let max=Number(state.budget||999),q=els.q.value.toLowerCase().trim();let list=SHOES.filter(s=>s.price<=max);if(q)list=list.filter(s=>JSON.stringify(s).toLowerCase().includes(q));if(els.category.value)list=list.filter(s=>s.category===els.category.value);return list.sort((a,b)=>score(b)-score(a))}
function bar(l,v){return `<div class="scoreRow"><span>${l}</span><div class="bar"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div>`}
function why(s){let r=[];if(s.widthScore>=85)r.push(`Matches your fit preference: ${s.width.toLowerCase()}.`);if(['half','sub2','marathon','10miler','ultra'].includes(state.goal))r.push(`Strong long-run score (${s.longrun}/100), useful for ${labelFor('goal',state.goal).toLowerCase()}.`);if(['5k','10k'].includes(state.goal)||state.focus==='speed')r.push(`Speed and tempo profile fits faster training (${s.speed}/100 speed, ${s.tempo}/100 tempo).`);if(state.focus==='cushion')r.push(`Cushion preference matches well (${s.cushion}/100).`);if(state.focus==='nonplate')r.push(s.plate==='No'?`No plate, so it should feel natural for daily use.`:`It is plated, which may be more aggressive.`);if(s.value>88)r.push(`Strong value score (${s.value}/100).`);if(!r.length)r.push(`It balances comfort, speed, fit, and value better than most shoes here.`);return r.slice(0,4)}
function downside(s){let d=[];if(s.price>200)d.push('Expensive compared with traditional daily trainers.');if(s.widthScore<75)d.push('Fit may be narrow or risky for wide feet.');if(s.plate!=='No')d.push('Plate may feel firm or aggressive for easy days.');if(s.cushion<82)d.push('Less cushioned than max-stack comfort shoes.');if(!d.length)d.push('Few major concerns based on your profile.');return d}
function dna(s){let tags=[];if(s.widthScore>=85)tags.push('Wide-foot friendly');if(s.longrun>=90)tags.push('Long runs');if(s.daily>=90)tags.push('Daily trainer');if(s.recovery>=90)tags.push('Recovery');if(s.tempo>=90)tags.push('Speed work');if(s.race>=85)tags.push('Race-ready');if(s.value>=90)tags.push('Best value');if(s.plate!=='No')tags.push('Plated');return tags}
function card(s,i,small=false){return `<article class="${small?'miniCard':'resultCard'}"><span class="pill good">#${i} • ${score(s)}/100</span><h3 class="shoeName">${s.name}</h3><div class="meta">${s.brand} • ${s.category} • $${s.price}</div><div class="pillRow">${dna(s).map(x=>`<span class="pill">${x}</span>`).join('')}</div><p>${s.note}</p>${bar('Fit',s.widthScore)}${bar('Cushion',s.cushion)}${bar('Speed',s.speed)}<details class="explain"><summary>Explain this recommendation</summary><ul>${why(s).map(x=>`<li>${x}</li>`).join('')}</ul><b>Possible downsides</b><ul>${downside(s).map(x=>`<li>${x}</li>`).join('')}</ul></details><div class="actions"><a class="linkbtn" href="${s.link}" target="_blank">Research shoe</a></div></article>`}
function shoeCard(s,i){let checked=selected.has(s.id);return `<article class="shoeCard" data-id="${s.id}"><div class="cardTop"><div><div class="shoeName">${i}. ${s.name}</div><div class="meta">${s.brand} • ${s.category} • $${s.price}</div></div><div class="match">${score(s)}</div></div><div class="pillRow"><span class="pill ${widthClass(s)}">👣 ${s.width}</span><span class="pill">☁️ ${s.cushion}</span><span class="pill">⚡ ${s.speed}</span><span class="pill">💰 ${s.value}</span></div><p class="muted">${s.note}</p>${bar('Fit',s.widthScore)}${bar('Speed',s.speed)}<div class="actions"><label onclick="event.stopPropagation()" class="checkbox"><input data-check="${s.id}" type="checkbox" ${checked?'checked':''}> Compare</label><a onclick="event.stopPropagation()" class="linkbtn" href="${s.link}" target="_blank">Research</a></div><div class="details"><div class="specs"><div class="spec"><b>Foam</b>${s.foam}</div><div class="spec"><b>Plate</b>${s.plate}</div><div class="spec"><b>Long run</b>${s.longrun}/100</div><div class="spec"><b>Tempo</b>${s.tempo}/100</div><div class="spec"><b>Recovery</b>${s.recovery}/100</div><div class="spec"><b>Race</b>${s.race}/100</div></div></div></article>`}
function renderStepper(){els.stepper.innerHTML=[0,1,2,3,4,5].map(i=>`<div class="dot ${i<=step?'active':''}"></div>`).join('');document.querySelectorAll('.step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===step));document.getElementById('prevBtn').disabled=step===0;document.getElementById('nextBtn').classList.toggle('hidden',step===5);document.getElementById('runBtn').classList.toggle('hidden',step!==5)}
function renderLive(){let list=filtered(),b=list[0];els.liveTitle.textContent=`${b.name} is leading.`;els.liveSummary.textContent=`Current match: ${score(b)}/100 based on ${labelFor('goal',state.goal)}, ${labelFor('fit',state.fit)}, ${labelFor('focus',state.focus)}, and ${labelFor('budget',state.budget)}.`;els.liveReasons.innerHTML=why(b).map(x=>`<div class="reason">${x}</div>`).join('')}
function renderReport(){let list=filtered(),best=list[0];els.reportSummary.textContent=`Goal: ${labelFor('goal',state.goal)} • Fit: ${labelFor('fit',state.fit)} • Priority: ${labelFor('focus',state.focus)} • Budget: ${labelFor('budget',state.budget)}`;els.perfectMatch.innerHTML=`<div><p class="eyebrow">Perfect Match</p><h2>${best.name}</h2><p>${best.note}</p><div class="pillRow">${dna(best).map(x=>`<span class="pill">${x}</span>`).join('')}</div><details class="explain" open><summary>Why this is #1</summary><ul>${why(best).map(x=>`<li>${x}</li>`).join('')}</ul><b>Possible downsides</b><ul>${downside(best).map(x=>`<li>${x}</li>`).join('')}</ul></details></div><div class="scoreHero">${score(best)}</div>`;els.topFive.innerHTML=list.slice(0,5).map((s,i)=>card(s,i+1,true)).join('');els.nearMisses.innerHTML=list.slice(5,9).map((s,i)=>`<div class="miniCard"><b>${s.name}</b><p class="muted">${s.category} • ${score(s)}/100</p><p>Close, but not as strong as your top picks because another shoe fits your profile better.</p></div>`).join('');let avoided=[...SHOES].filter(s=>score(s)<70||s.widthScore<72||s.price>Number(state.budget||999)).sort((a,b)=>score(a)-score(b)).slice(0,4);els.avoidList.innerHTML=avoided.map(s=>`<div class="miniCard"><b>${s.name}</b><p class="muted">${s.category} • ${score(s)}/100</p><p>${s.widthScore<75?'Likely too narrow for your fit preference.':s.price>Number(state.budget||999)?'Outside your selected budget.':'Lower match for your current profile.'}</p></div>`).join('');renderRotation(list)}
function renderRotation(list){let daily=list.find(s=>s.daily>88&&s.plate==='No')||list[0],workout=list.find(s=>s.tempo>90)||list[1]||list[0],long=list.find(s=>s.longrun>92)||list[0],race=list.find(s=>s.race>85)||workout;els.rotation.innerHTML=[['Daily Trainer',daily],['Workout Shoe',workout],['Long Run Shoe',long],['Race / Fast Option',race]].map(([l,s])=>`<div class="rotationCard"><b>${l}</b><br>${s.name}<br><span class="muted">${s.category} • Match ${score(s)}</span></div>`).join('')}
function renderCompare(){let p=document.getElementById('comparePanel'),g=document.getElementById('compareGrid'),list=SHOES.filter(s=>selected.has(s.id)).sort((a,b)=>score(b)-score(a));p.style.display=list.length?'block':'none';g.innerHTML=list.map(s=>`<div class="compareCard"><b>${s.name}</b><br><span class="muted">${s.category} • $${s.price}</span>${bar('Match',score(s))}${bar('Fit',s.widthScore)}${bar('Cushion',s.cushion)}${bar('Speed',s.speed)}<button data-remove="${s.id}">Remove</button></div>`).join('')}
function renderDatabase(){let list=filtered();els.count.textContent=list.length;els.grid.innerHTML=list.map((s,i)=>shoeCard(s,i+1)).join('')}
function renderAll(){renderStepper();renderLive();renderReport();renderCompare();renderDatabase()}
document.addEventListener('click',e=>{let choice=e.target.closest('.chips button');if(choice){let group=choice.parentElement.dataset.group;state[group]=choice.dataset.value;choice.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));choice.classList.add('active');renderAll();return}let cb=e.target.closest('[data-check]');if(cb){let id=Number(cb.dataset.check);cb.checked?selected.add(id):selected.delete(id);localStorage.setItem('selectedShoesV7',JSON.stringify([...selected]));renderCompare();return}let rm=e.target.closest('[data-remove]');if(rm){selected.delete(Number(rm.dataset.remove));localStorage.setItem('selectedShoesV7',JSON.stringify([...selected]));renderAll();return}let sc=e.target.closest('.shoeCard');if(sc)sc.classList.toggle('open')});
document.getElementById('prevBtn').onclick=()=>{step=Math.max(0,step-1);renderAll()};document.getElementById('nextBtn').onclick=()=>{step=Math.min(5,step+1);renderAll()};document.getElementById('runBtn').onclick=()=>{document.getElementById('thinking').classList.remove('hidden');setTimeout(()=>{document.getElementById('thinking').classList.add('hidden');document.getElementById('report').scrollIntoView({behavior:'smooth'});renderAll()},900)};['input','change'].forEach(ev=>['q','category'].forEach(id=>els[id].addEventListener(ev,renderAll)));['likedShoes','avoidInput'].forEach(id=>document.getElementById(id).addEventListener('input',renderAll));document.getElementById('reset').onclick=()=>{els.q.value='';els.category.value='';renderAll()};renderAll();