const state={intent:'dailyTrainer',goal:'half',fit:'wide',focus:'balanced',budget:'999'};let step=0;
const els={q:document.getElementById('q'),category:document.getElementById('category'),intentFilter:document.getElementById('intentFilter'),grid:document.getElementById('grid'),count:document.getElementById('count'),liveTitle:document.getElementById('liveTitle'),liveSummary:document.getElementById('liveSummary'),liveReasons:document.getElementById('liveReasons'),reportSummary:document.getElementById('reportSummary'),perfectMatch:document.getElementById('perfectMatch'),topFive:document.getElementById('topFive'),nearMisses:document.getElementById('nearMisses'),avoidList:document.getElementById('avoidList'),rotation:document.getElementById('rotation'),stepper:document.getElementById('stepper')};
[...new Set(SHOES.map(s=>s.category))].sort().forEach(c=>{let o=document.createElement('option');o.value=c;o.textContent=c;els.category.appendChild(o)});
let selected=new Set(JSON.parse(localStorage.getItem('selectedShoesV8')||'[]'));
const intentLabels={raceDay:'Race-day shoe',tempoWorkout:'Tempo / workout trainer',dailyTrainer:'Daily trainer',longRun:'Long-run shoe',recovery:'Recovery / max cushion',stability:'Stability / support',valuePick:'Best value',rotation:'Full rotation'};
function widthClass(s){return s.widthScore>=85?'good':s.widthScore<75?'bad':'warn'}
function labelFor(group,val){let btn=document.querySelector(`[data-group="${group}"] [data-value="${val}"]`);return btn?btn.textContent:(intentLabels[val]||val)}
function likedTerms(){return (document.getElementById('likedShoes').value||'').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean)}
function avoidTerms(){return (document.getElementById('avoidInput').value||'').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean)}
function baseGoalScore(s){let g=state.goal,b=0;if(g==='5k')b=s.speed*.34+s.tempo*.28+s.race*.18+s.value*.10+s.stability*.05+s.daily*.05;if(g==='10k')b=s.speed*.28+s.tempo*.28+s.race*.16+s.daily*.12+s.cushion*.08+s.value*.08;if(g==='10miler')b=s.tempo*.24+s.longrun*.22+s.speed*.18+s.cushion*.14+s.daily*.12+s.value*.10;if(g==='half'||g==='sub2')b=s.daily*.22+s.longrun*.25+s.tempo*.20+s.speed*.14+s.cushion*.10+s.stability*.05+s.value*.04;if(g==='marathon')b=s.longrun*.32+s.cushion*.22+s.daily*.16+s.stability*.12+s.tempo*.10+s.value*.08;if(g==='ultra')b=s.longrun*.35+s.cushion*.25+s.stability*.18+s.recovery*.12+s.value*.10;if(g==='daily')b=s.daily*.32+s.cushion*.18+s.stability*.15+s.value*.15+s.recovery*.10+s.longrun*.10;return b}
function score(s){let intent=state.intent==='rotation'?'rotation':state.intent;let b=(s.intent?.[intent]??s.daily)*.62 + baseGoalScore(s)*.23 + s.value*.05 + s.stability*.05 + s.cushion*.05;
 if(state.fit==='wide')b+=(s.widthScore-75)*.25;if(state.fit==='extraWide')b+=(s.widthScore-75)*.43;if(state.fit==='standard'||state.fit==='unknown')b+=Math.min(s.widthScore,85)*.025;if(state.fit==='narrow')b+=s.speed*.035;
 if(state.focus==='cushion')b+=s.cushion*.13;if(state.focus==='speed')b+=s.speed*.13;if(state.focus==='stable')b+=s.stability*.13;if(state.focus==='value')b+=s.value*.16-(s.price>200?4:0);if(state.focus==='nonplate'&&s.plate==='No')b+=8;if(state.focus==='nonplate'&&s.plate!=='No')b-=8;if(state.focus==='race')b+=s.race*.14;
 if(state.intent==='raceDay'&&s.race<70)b-=12;if(state.intent==='tempoWorkout'&&s.tempo<78)b-=10;if(state.intent==='recovery'&&s.recovery<80)b-=12;if(state.intent==='stability'&&s.stability<86)b-=12;if(state.intent==='dailyTrainer'&&s.daily<80)b-=8;
 likedTerms().forEach(t=>{if(JSON.stringify(s).toLowerCase().includes(t))b+=5});avoidTerms().forEach(t=>{if(JSON.stringify(s).toLowerCase().includes(t))b-=10;if(t==='narrow'&&s.widthScore<75)b-=12;if(t==='plated'&&s.plate!=='No')b-=10;if(t==='firm'&&s.cushion<82)b-=8});
 return Math.round(Math.max(0,Math.min(100,b)))}
function filtered(){let max=Number(state.budget||999),q=els.q.value.toLowerCase().trim();let list=SHOES.filter(s=>s.price<=max);if(q)list=list.filter(s=>JSON.stringify(s).toLowerCase().includes(q));if(els.category.value)list=list.filter(s=>s.category===els.category.value);if(els.intentFilter.value)list=list.filter(s=>(s.intent?.[els.intentFilter.value]??0)>=78);return list.sort((a,b)=>score(b)-score(a))}
function bar(l,v){return `<div class="scoreRow"><span>${l}</span><div class="bar"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div>`}
function why(s){let intent=state.intent==='rotation'?'rotation':state.intent;let r=[];r.push(`Strong ${intentLabels[state.intent].toLowerCase()} fit: ${s.intent?.[intent]??score(s)}/100 for this shoe purpose.`);if(s.widthScore>=85)r.push(`Good fit compatibility: ${s.width.toLowerCase()}.`);if(state.intent==='raceDay')r.push(`Race score ${s.race}/100 and speed score ${s.speed}/100.`);if(state.intent==='tempoWorkout')r.push(`Tempo score ${s.tempo}/100 for faster sessions.`);if(state.intent==='dailyTrainer')r.push(`Daily training score ${s.daily}/100.`);if(state.intent==='longRun')r.push(`Long-run score ${s.longrun}/100.`);if(state.intent==='recovery')r.push(`Recovery score ${s.recovery}/100 and cushion score ${s.cushion}/100.`);if(state.intent==='stability')r.push(`Stability/support score ${s.stability}/100.`);if(state.intent==='valuePick')r.push(`Value score ${s.value}/100 with a listed price around $${s.price}.`);if(s.longevityMiles)r.push(`Estimated longevity: ${s.longevityMiles}.`);return r.slice(0,5)}
function downside(s){let d=[];if(s.price>250)d.push('Premium price; not ideal if value is the top priority.');if(s.widthScore<75)d.push('Potentially narrow or risky for wide feet.');if(state.intent==='dailyTrainer'&&s.plate!=='No')d.push('Plated design may be less relaxed for easy daily mileage.');if(state.intent==='raceDay'&&s.plate==='No'&&s.race<90)d.push('May not feel as aggressive as a true race-day super shoe.');if(state.intent==='recovery'&&s.speed>92)d.push('May feel too performance-oriented for pure recovery days.');if(!d.length)d.push('No major concerns based on your selected purpose.');return d}
function dna(s){let tags=[];if(s.intent.raceDay>=86)tags.push('Race day');if(s.intent.tempoWorkout>=88)tags.push('Tempo');if(s.intent.dailyTrainer>=88)tags.push('Daily');if(s.intent.longRun>=90)tags.push('Long runs');if(s.intent.recovery>=90)tags.push('Recovery');if(s.intent.stability>=92)tags.push('Stability');if(s.intent.valuePick>=92)tags.push('Value');if(s.widthScore>=85)tags.push('Wide-friendly');if(s.plate!=='No')tags.push('Plated');return tags.slice(0,7)}
function resultCard(s,i,small=false){return `<article class="${small?'miniCard':'resultCard'}"><span class="pill good">#${i} • ${score(s)}/100</span><span class="pill intentPill">${intentLabels[state.intent]}</span><h3 class="shoeName">${s.name}</h3><div class="meta">${s.brand} • ${s.category} • $${s.price}</div><div class="pillRow">${dna(s).map(x=>`<span class="pill">${x}</span>`).join('')}</div><p>${s.note}</p>${bar('Purpose',s.intent?.[state.intent==='rotation'?'rotation':state.intent]??score(s))}${bar('Longevity',s.longevityScore||70)}${bar('Fit',s.widthScore)}${bar('Speed',s.speed)}<details class="explain"><summary>Explain this recommendation</summary><ul>${why(s).map(x=>`<li>${x}</li>`).join('')}</ul><b>Expected longevity</b><ul><li>${s.longevityMiles||'300-500 miles'} — ${s.longevityNote||'Mileage varies by runner, surface, and rotation.'}</li></ul><b>Possible downsides</b><ul>${downside(s).map(x=>`<li>${x}</li>`).join('')}</ul></details><div class="actions"><a class="linkbtn" href="${s.link}" target="_blank">Research shoe</a></div></article>`}
function shoeCard(s,i){let checked=selected.has(s.id);return `<article class="shoeCard" data-id="${s.id}"><div class="cardTop"><div><div class="shoeName">${i}. ${s.name}</div><div class="meta">${s.brand} • ${s.category} • $${s.price}</div></div><div class="match">${score(s)}</div></div><div class="pillRow"><span class="pill intentPill">${intentLabels[state.intent]}</span><span class="pill ${widthClass(s)}">👣 ${s.width}</span><span class="pill">Race ${s.intent.raceDay}</span><span class="pill">Tempo ${s.intent.tempoWorkout}</span><span class="pill">Daily ${s.intent.dailyTrainer}</span><span class="pill">⏱ ${s.longevityMiles||'300-500 miles'}</span></div><p class="muted">${s.note}</p>${bar('Purpose',s.intent?.[state.intent==='rotation'?'rotation':state.intent]??score(s))}${bar('Longevity',s.longevityScore||70)}${bar('Fit',s.widthScore)}<div class="actions"><label onclick="event.stopPropagation()" class="checkbox"><input data-check="${s.id}" type="checkbox" ${checked?'checked':''}> Compare</label><a onclick="event.stopPropagation()" class="linkbtn" href="${s.link}" target="_blank">Research</a></div><div class="details"><div class="specs"><div class="spec"><b>Race day</b>${s.intent.raceDay}/100</div><div class="spec"><b>Tempo</b>${s.intent.tempoWorkout}/100</div><div class="spec"><b>Daily</b>${s.intent.dailyTrainer}/100</div><div class="spec"><b>Long run</b>${s.intent.longRun}/100</div><div class="spec"><b>Recovery</b>${s.intent.recovery}/100</div><div class="spec"><b>Stability</b>${s.intent.stability}/100</div><div class="spec"><b>Longevity</b>${s.longevityMiles||'300-500 miles'}</div><div class="spec"><b>Durability</b>${s.longevityScore||70}/100</div><div class="spec"><b>Foam</b>${s.foam}</div><div class="spec"><b>Plate</b>${s.plate}</div></div></div></article>`}
function renderStepper(){els.stepper.innerHTML=[0,1,2,3,4,5,6].map(i=>`<div class="dot ${i<=step?'active':''}"></div>`).join('');document.querySelectorAll('.step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===step));document.getElementById('prevBtn').disabled=step===0;document.getElementById('nextBtn').classList.toggle('hidden',step===6);document.getElementById('runBtn').classList.toggle('hidden',step!==6)}
function renderLive(){let list=filtered(),b=list[0];els.liveTitle.textContent=`${b.name} is leading.`;els.liveSummary.textContent=`Current match: ${score(b)}/100 for ${intentLabels[state.intent].toLowerCase()}, ${labelFor('goal',state.goal)}, ${labelFor('fit',state.fit)}, and ${labelFor('budget',state.budget)}.`;els.liveReasons.innerHTML=why(b).map(x=>`<div class="reason">${x}</div>`).join('')}
function renderReport(){let list=filtered(),best=list[0],purpose=state.intent==='rotation'?'rotation':state.intent;els.reportSummary.textContent=`Purpose: ${intentLabels[state.intent]} • Goal: ${labelFor('goal',state.goal)} • Fit: ${labelFor('fit',state.fit)} • Priority: ${labelFor('focus',state.focus)} • Budget: ${labelFor('budget',state.budget)}`;els.perfectMatch.innerHTML=`<div><p class="eyebrow">Perfect Match</p><h2>${best.name}</h2><p>${best.note}</p><div class="pillRow">${dna(best).map(x=>`<span class="pill">${x}</span>`).join('')}</div><details class="explain" open><summary>Why this is #1 for ${intentLabels[state.intent].toLowerCase()}</summary><ul>${why(best).map(x=>`<li>${x}</li>`).join('')}</ul><b>Expected longevity</b><ul><li>${best.longevityMiles||'300-500 miles'} — ${best.longevityNote||'Mileage varies by runner, surface, and rotation.'}</li></ul><b>Possible downsides</b><ul>${downside(best).map(x=>`<li>${x}</li>`).join('')}</ul></details></div><div class="scoreHero">${score(best)}</div>`;els.topFive.innerHTML=list.slice(0,5).map((s,i)=>resultCard(s,i+1,true)).join('');els.nearMisses.innerHTML=list.slice(5,9).map(s=>`<div class="miniCard"><b>${s.name}</b><p class="muted">${s.category} • ${score(s)}/100</p><p>Close, but the top picks score better for ${intentLabels[state.intent].toLowerCase()}.</p></div>`).join('');let avoided=[...SHOES].filter(s=>score(s)<70||s.widthScore<72||s.price>Number(state.budget||999)||(state.intent==='raceDay'&&s.intent.raceDay<70)||(state.intent==='tempoWorkout'&&s.intent.tempoWorkout<72)).sort((a,b)=>score(a)-score(b)).slice(0,4);els.avoidList.innerHTML=avoided.map(s=>`<div class="miniCard"><b>${s.name}</b><p class="muted">${s.category} • ${score(s)}/100</p><p>${s.widthScore<75?'Likely too narrow for your fit preference.':s.price>Number(state.budget||999)?'Outside your selected budget.':`Not a strong match for ${intentLabels[state.intent].toLowerCase()}.`}</p></div>`).join('');renderRotation(list)}
function renderRotation(list){let daily=SHOES.sort((a,b)=>b.intent.dailyTrainer-a.intent.dailyTrainer)[0],workout=SHOES.sort((a,b)=>b.intent.tempoWorkout-a.intent.tempoWorkout)[0],long=SHOES.sort((a,b)=>b.intent.longRun-a.intent.longRun)[0],race=SHOES.sort((a,b)=>b.intent.raceDay-a.intent.raceDay)[0],recovery=SHOES.sort((a,b)=>b.intent.recovery-a.intent.recovery)[0];els.rotation.innerHTML=[['Daily Trainer',daily],['Workout Shoe',workout],['Long Run Shoe',long],['Race-Day Shoe',race],['Recovery Shoe',recovery]].map(([l,s])=>`<div class="rotationCard"><b>${l}</b><br>${s.name}<br><span class="muted">${s.category} • ${s.intent[l.includes('Race')?'raceDay':l.includes('Workout')?'tempoWorkout':l.includes('Long')?'longRun':l.includes('Recovery')?'recovery':'dailyTrainer']}/100</span></div>`).join('')}
function renderCompare(){let p=document.getElementById('comparePanel'),g=document.getElementById('compareGrid'),list=SHOES.filter(s=>selected.has(s.id)).sort((a,b)=>score(b)-score(a));p.style.display=list.length?'block':'none';g.innerHTML=list.map(s=>`<div class="compareCard"><b>${s.name}</b><br><span class="muted">${s.category} • $${s.price}</span>${bar('Match',score(s))}${bar('Race',s.intent.raceDay)}${bar('Tempo',s.intent.tempoWorkout)}${bar('Daily',s.intent.dailyTrainer)}${bar('Longevity',s.longevityScore||70)}${bar('Fit',s.widthScore)}<button data-remove="${s.id}">Remove</button></div>`).join('')}
function renderDatabase(){let list=filtered();els.count.textContent=list.length;els.grid.innerHTML=list.map((s,i)=>shoeCard(s,i+1)).join('')}
function renderAll(){renderStepper();renderLive();renderReport();renderCompare();renderDatabase()}
document.addEventListener('click',e=>{let choice=e.target.closest('.chips button');if(choice){let group=choice.parentElement.dataset.group;state[group]=choice.dataset.value;choice.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));choice.classList.add('active');renderAll();return}let cb=e.target.closest('[data-check]');if(cb){let id=Number(cb.dataset.check);cb.checked?selected.add(id):selected.delete(id);localStorage.setItem('selectedShoesV8',JSON.stringify([...selected]));renderCompare();return}let rm=e.target.closest('[data-remove]');if(rm){selected.delete(Number(rm.dataset.remove));localStorage.setItem('selectedShoesV8',JSON.stringify([...selected]));renderAll();return}let sc=e.target.closest('.shoeCard');if(sc)sc.classList.toggle('open')});
document.getElementById('prevBtn').onclick=()=>{step=Math.max(0,step-1);renderAll()};document.getElementById('nextBtn').onclick=()=>{step=Math.min(6,step+1);renderAll()};document.getElementById('runBtn').onclick=()=>{document.getElementById('thinking').classList.remove('hidden');setTimeout(()=>{document.getElementById('thinking').classList.add('hidden');document.getElementById('report').scrollIntoView({behavior:'smooth'});renderAll()},900)};['input','change'].forEach(ev=>['q','category','intentFilter'].forEach(id=>els[id].addEventListener(ev,renderAll)));['likedShoes','avoidInput'].forEach(id=>document.getElementById(id).addEventListener('input',renderAll));document.getElementById('reset').onclick=()=>{els.q.value='';els.category.value='';els.intentFilter.value='';renderAll()};renderAll();

function buildFeedbackMessage(){
  const name = document.getElementById('feedbackName')?.value.trim() || 'Anonymous';
  const type = document.getElementById('feedbackType')?.value || 'General feedback';
  const text = document.getElementById('feedbackText')?.value.trim() || '';
  const profile = `Current advisor settings:
- Intent: ${intentLabels[state.intent]}
- Goal: ${labelFor('goal',state.goal)}
- Fit: ${labelFor('fit',state.fit)}
- Focus: ${labelFor('focus',state.focus)}
- Budget: ${labelFor('budget',state.budget)}`;
  return `Name: ${name}

Feedback type: ${type}

Feedback:
${text || '[No feedback entered]'}

${profile}

Page: ${window.location.href}`;
}

function setupFeedback(){
  const send = document.getElementById('sendFeedback');
  const copy = document.getElementById('copyFeedback');
  if(!send || !copy) return;

  send.addEventListener('click', () => {
    const subject = encodeURIComponent('Running Shoe Finder Feedback');
    const body = encodeURIComponent(buildFeedbackMessage());
    window.location.href = `mailto:corkacola28@gmail.com?subject=${subject}&body=${body}`;
  });

  copy.addEventListener('click', async () => {
    const message = buildFeedbackMessage();
    try{
      await navigator.clipboard.writeText(message);
      copy.textContent = 'Copied!';
      setTimeout(()=>copy.textContent='Copy feedback',1600);
    }catch(e){
      alert(message);
    }
  });
}
setupFeedback();
