const els={q:document.getElementById('q'),goal:document.getElementById('goal'),fit:document.getElementById('fit'),focus:document.getElementById('focus'),category:document.getElementById('category'),grid:document.getElementById('grid'),count:document.getElementById('count'),quickPicks:document.getElementById('quickPicks'),summaryPills:document.getElementById('summaryPills')};
[...new Set(SHOES.map(s=>s.category))].sort().forEach(c=>{const o=document.createElement('option');o.textContent=c;o.value=c;els.category.appendChild(o)});
let selected=new Set(JSON.parse(localStorage.getItem('selectedShoes')||'[]'));const notes=document.getElementById('notes');notes.value=localStorage.getItem('shoeFinderNotes')||'';notes.addEventListener('input',e=>localStorage.setItem('shoeFinderNotes',e.target.value));
function score(s){let g=els.goal.value,f=els.fit.value,focus=els.focus.value,b=0;if(g==='sub2')b=s.daily*.22+s.longrun*.25+s.tempo*.20+s.speed*.14+s.cushion*.10+s.stability*.05+s.value*.04;if(g==='daily')b=s.daily*.32+s.cushion*.18+s.stability*.15+s.value*.15+s.recovery*.10+s.longrun*.10;if(g==='marathon')b=s.longrun*.32+s.cushion*.22+s.daily*.16+s.stability*.12+s.tempo*.10+s.value*.08;if(g==='speed')b=s.speed*.32+s.tempo*.30+s.race*.18+s.value*.10+s.daily*.10;if(g==='comfort')b=s.recovery*.34+s.cushion*.30+s.widthScore*.15+s.stability*.12+s.value*.09;if(g==='budget')b=s.value*.38+s.daily*.22+s.longrun*.14+s.cushion*.12+s.speed*.08+s.stability*.06;if(f==='wide')b+=(s.widthScore-75)*.28;if(f==='extraWide')b+=(s.widthScore-75)*.45;if(f==='standard')b+=Math.min(s.widthScore,85)*.03;if(f==='narrow')b+=s.speed*.04;if(focus==='cushion')b+=s.cushion*.18;if(focus==='speed')b+=s.speed*.18;if(focus==='stable')b+=s.stability*.18;if(focus==='value')b+=s.value*.20-(s.price>200?4:0);if(focus==='nonplate'&&s.plate==='No')b+=8;if(focus==='nonplate'&&s.plate!=='No')b-=7;return Math.round(Math.max(0,Math.min(100,b)))}
function bar(l,v){return `<div class="scoreRow"><span>${l}</span><div class="bar"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div>`}
function widthClass(s){return s.widthScore>=85?'good':s.widthScore<75?'bad':'warn'}
function card(s,r){let checked=selected.has(s.id);return `<article class="card" data-id="${s.id}" tabindex="0" role="button"><div class="cardTop"><div><div class="name">${r}. ${s.name}</div><div class="meta">${s.brand} • ${s.category} • $${s.price} • Plate: ${s.plate}</div></div><div class="rank">${score(s)}</div></div><div class="tags"><span class="tag ${widthClass(s)}">👣 ${s.width}</span><span class="tag">☁️ Cushion ${s.cushion}</span><span class="tag">⚡ Speed ${s.speed}</span><span class="tag">💰 Value ${s.value}</span></div><p class="verdict">${s.note}</p>${bar('Fit',s.widthScore)}${bar('Cushion',s.cushion)}${bar('Speed',s.speed)}${bar('Value',s.value)}<div class="actions"><label class="checkbox" onclick="event.stopPropagation()"><input type="checkbox" data-check="${s.id}" ${checked?'checked':''}> Compare</label><a class="linkbtn" href="${s.link}" target="_blank" rel="noopener" onclick="event.stopPropagation()">Shop / info</a></div><div class="details"><div class="specs"><div class="spec"><b>Best use</b>${s.category}</div><div class="spec"><b>Foam</b>${s.foam}</div><div class="spec"><b>Long run</b>${s.longrun}/100</div><div class="spec"><b>Tempo</b>${s.tempo}/100</div><div class="spec"><b>Recovery</b>${s.recovery}/100</div><div class="spec"><b>Race-ish</b>${s.race}/100</div></div><p class="small"><b>Fit note:</b> ${s.width}. If you are 2E or wider, prioritize models with actual Wide/2E sizing when possible.</p></div></article>`}
function getList(){let q=els.q.value.toLowerCase().trim();let list=SHOES.filter(s=>!q||JSON.stringify(s).toLowerCase().includes(q));if(els.category.value)list=list.filter(s=>s.category===els.category.value);return list.sort((a,b)=>score(b)-score(a))}
function renderCompare(){let p=document.getElementById('comparePanel'),g=document.getElementById('compareGrid'),list=SHOES.filter(s=>selected.has(s.id)).sort((a,b)=>score(b)-score(a));p.style.display=list.length?'block':'none';g.innerHTML=list.map(s=>`<div class="compareCard"><b>${s.name}</b><div class="small">${s.category} • $${s.price}</div>${bar('Match',score(s))}${bar('Fit',s.widthScore)}${bar('Cushion',s.cushion)}${bar('Speed',s.speed)}${bar('Value',s.value)}<button class="light remove" data-remove="${s.id}">Remove</button></div>`).join('')}
function render(){let list=getList();els.count.textContent=list.length;els.grid.innerHTML=list.map((s,i)=>card(s,i+1)).join('');let picks=list.slice(0,4),labels=['Best match','Runner-up','Best alternate','Also consider'];els.quickPicks.innerHTML=picks.map((s,i)=>`<div class="rec"><b>${labels[i]}</b>${s.name}<br><span class="small">${s.note} • Score ${score(s)}</span></div>`).join('');els.summaryPills.innerHTML=['🎯 '+els.goal.options[els.goal.selectedIndex].text.replace('Goal: ',''),'👣 '+els.fit.options[els.fit.selectedIndex].text.replace('Fit: ',''),'🔎 '+els.focus.options[els.focus.selectedIndex].text.replace('Focus: ',''),'👟 '+SHOES.length+' shoes'].map(x=>`<span class="pill">${x}</span>`).join('');renderCompare()}
document.addEventListener('click',e=>{let cb=e.target.closest('[data-check]');if(cb){let id=Number(cb.dataset.check);cb.checked?selected.add(id):selected.delete(id);localStorage.setItem('selectedShoes',JSON.stringify([...selected]));renderCompare();return}let rem=e.target.closest('[data-remove]');if(rem){selected.delete(Number(rem.dataset.remove));localStorage.setItem('selectedShoes',JSON.stringify([...selected]));render();return}let c=e.target.closest('.card');if(c)c.classList.toggle('open')});
['input','change'].forEach(evt=>['q','goal','fit','focus','category'].forEach(id=>els[id].addEventListener(evt,render)));document.getElementById('reset').addEventListener('click',()=>{els.q.value='';els.goal.value='sub2';els.fit.value='wide';els.focus.value='balanced';els.category.value='';render()});render();